language: dart

dart:
  - stable

dart_task:
  - dartfmt: true
  - test: --platform vm
  - test: --platform chrome
  - dartanalyzer: --fatal-warnings lib

cache:
  directories:
    - $HOME/.pub-cache
    - .dart_tool