name: json_util
description: Type-safe JSON-encoding and JSON-decoding utilities for Dart.
version: 0.6.0
homepage: https://github.com/parsodyl/json_util

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.16.6
  benchmark_harness: ^2.0.0
