name: json_util
description: Type-safe JSON-encoding and JSON-decoding utilities for Dart.
version: 0.5.0
homepage: https://github.com/parsodyl/json_util
author: Daniele Paradiso <parsodyl@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.9.3
  test_coverage: ^0.4.0
  benchmark_harness: ^1.0.5
